### ISSUE TITLE
rollbackFailedOptional: verb npm-session xxx

### ISSUE THREAD

**Issue by sakiss** [dgrammatiko/compress#2]
Every time i try to execute the script
`npx --no-install github:dgrammatiko/compress`

I get:
`rollbackFailedOptional: verb npm-session xxx `
and npm stops there forever.

I tried [every solution i found](https://stackoverflow.com/questions/46011546/npm-install-error-rollbackfailedoptional) related with that error, even uninstalled and re-installed npm and npx but still persists.

Seems to happen only with that script as i tried several others and work.
It was working initially but suddenly i got this and is no longer usable.
Btw. I am not behind any proxy server neither i use VPN. Also the npm registry is the default one.

Any idea?

**Comment by dgrammatiko** [comment]
Can you try `npx github:dgrammatiko/compress` instead of `npx --no-install github:dgrammatiko/compress` ?

**Comment by sakiss** [comment]
That worked, though i uninstalled again node and all it's dependencies.
I suppose something went wrong with some of them.
